# Generated by Django 5.2.11 on 2026-02-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='submitted_by_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='submitted_by_username',
        ),
    ]
