services:
  postgres:
    build:
      context: ../../backend/database
    image: ph-postgres:18.1-alpine
    restart: unless-stopped
    env_file: ./prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  n8n:
    build:
      context: ../../backend/n8n
    image: ph-n8n:2.4.7
    restart: unless-stopped
    env_file: ./prod.env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy

  django:
    build:
      context: ../../backend/django
    image: ph-django:0.1
    restart: unless-stopped
    env_file: ./prod.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  n8n_data:
